@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

class kunde
class ordre
class skur
class carport
class tilbudsberegning
class sælger


kunde *- ordre
admin *- ordre
ordre -- carport
carport -- sælger
carport -- skur
skur -- sælger
sælger -> tilbudsberegning
tilbudsberegning -> sælger
sælger -- kunde

@enduml